// Code generated by `wizig codegen`. DO NOT EDIT.
// Placeholder — overwritten during codegen with app-specific API declarations.
#ifndef WIZIG_GENERATED_API_H
#define WIZIG_GENERATED_API_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Generated API methods (added by wizig codegen)

#ifdef __cplusplus
}
#endif

#endif
