//! Lockfile renderer for discovered plugin manifests.
const std = @import("std");
const MavenDependency = @import("../manifest.zig").MavenDependency;
const SpmDependency = @import("../manifest.zig").SpmDependency;
const PluginRecord = @import("types.zig").PluginRecord;
const common = @import("render_common.zig");

/// Renders deterministic lockfile text for all plugin records.
pub fn renderLockfile(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(allocator, "# Code generated by `wizig plugin sync`. DO NOT EDIT.\n");
    try out.appendSlice(allocator, "format_version = 2\n\n");

    for (records) |record| {
        try out.appendSlice(allocator, "[[plugins]]\n");
        try out.appendSlice(allocator, "schema_version = 2\n");
        try out.appendSlice(allocator, "id = ");
        try common.appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, "\nversion = ");
        try common.appendQuoted(&out, allocator, record.manifest.version);
        try common.appendFmt(&out, allocator, "\napi_version = {d}\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "manifest_path = ");
        try common.appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, "\ncapabilities = ");
        try common.appendBracketedStringArray(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, "\nios_spm = ");
        try appendSpmTomlArray(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, "\nandroid_maven = ");
        try appendMavenTomlArray(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, "\n\n");
    }

    return out.toOwnedSlice(allocator);
}

/// Renders SPM dependency tuples in TOML inline-table array syntax.
fn appendSpmTomlArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const SpmDependency,
) !void {
    try out.append(allocator, '[');
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, "{ url = ");
        try common.appendQuoted(out, allocator, value.url);
        try out.appendSlice(allocator, ", requirement = ");
        try common.appendQuoted(out, allocator, value.requirement);
        try out.appendSlice(allocator, ", product = ");
        try common.appendQuoted(out, allocator, value.product);
        try out.appendSlice(allocator, " }");
    }
    try out.append(allocator, ']');
}

/// Renders Maven dependency tuples in TOML inline-table array syntax.
fn appendMavenTomlArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const MavenDependency,
) !void {
    try out.append(allocator, '[');
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, "{ coordinate = ");
        try common.appendQuoted(out, allocator, value.coordinate);
        try out.appendSlice(allocator, ", classifier = ");
        try common.appendQuoted(out, allocator, value.classifier);
        try out.appendSlice(allocator, ", scope = ");
        try common.appendQuoted(out, allocator, value.scope);
        try out.appendSlice(allocator, " }");
    }
    try out.append(allocator, ']');
}
