//! Generated static plugin registry used by tooling/runtime integration.
// Code generated by `ziggy plugin sync`. DO NOT EDIT.

/// Single plugin descriptor entry.
pub const RegisteredPlugin = struct {
    id: []const u8,
    version: []const u8,
    api_version: u32,
    manifest_path: []const u8,
    capabilities: []const []const u8,
    ios_spm: []const []const u8,
    android_maven: []const []const u8,
};

/// Statically-registered plugins discovered during sync.
pub const plugins: []const RegisteredPlugin = &.{
    .{
        .id = "dev.ziggy.hello",
        .version = "0.1.0",
        .api_version = 1,
        .manifest_path = "examples/plugin-hello/ziggy-plugin.toml",
        .capabilities = &.{"log"},
        .ios_spm = &.{},
        .android_maven = &.{},
    },
};
