// Code generated by `wizig plugin sync`. DO NOT EDIT.
package dev.wizig

data class PluginDescriptor(
    val id: String,
    val version: String,
    val apiVersion: UInt,
    val manifestPath: String,
    val capabilities: List<String>,
    val iosSpm: List<String>,
    val androidMaven: List<String>
)

object GeneratedPluginRegistrant {
    val plugins: List<PluginDescriptor> = listOf(
        PluginDescriptor(
            id = "dev.wizig.hello",
            version = "0.1.0",
            apiVersion = 1u,
            manifestPath = "examples/plugin-hello/wizig-plugin.toml",
            capabilities = listOf("log"),
            iosSpm = listOf(),
            androidMaven = listOf()
        ),
    )
}
