//! Runtime-packaged plugin registry collection and registrant generators.
const std = @import("std");
const PluginManifest = @import("manifest.zig").PluginManifest;

/// Plugin file path paired with parsed manifest contents.
pub const PluginRecord = struct {
    manifest_path: []u8,
    manifest: PluginManifest,

    /// Releases owned path/manifest data.
    pub fn deinit(self: *PluginRecord, allocator: std.mem.Allocator) void {
        allocator.free(self.manifest_path);
        self.manifest.deinit(allocator);
        self.* = undefined;
    }
};

/// In-memory registry of discovered plugins.
pub const Registry = struct {
    records: []PluginRecord,

    /// Releases all registry records and their owned allocations.
    pub fn deinit(self: *Registry, allocator: std.mem.Allocator) void {
        for (self.records) |*record| {
            record.deinit(allocator);
        }
        allocator.free(self.records);
        self.* = undefined;
    }
};

/// Collects plugin manifests from the given `plugins_dir`.
pub fn collectFromDir(
    allocator: std.mem.Allocator,
    io: std.Io,
    root_path: []const u8,
) !Registry {
    var root_dir = try std.Io.Dir.cwd().openDir(io, root_path, .{ .iterate = true });
    defer root_dir.close(io);

    var walker = try root_dir.walk(allocator);
    defer walker.deinit();

    var records = std.ArrayList(PluginRecord).empty;
    errdefer deinitRecordList(allocator, &records);

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.eql(u8, entry.basename, "wizig-plugin.toml")) continue;

        const manifest_text = try root_dir.readFileAlloc(io, entry.path, allocator, .limited(1024 * 1024));
        defer allocator.free(manifest_text);

        var manifest = try PluginManifest.parse(allocator, manifest_text);
        errdefer manifest.deinit(allocator);

        const manifest_path = try combineManifestPath(allocator, root_path, entry.path);
        errdefer allocator.free(manifest_path);

        try records.append(allocator, .{
            .manifest_path = manifest_path,
            .manifest = manifest,
        });
    }

    const records_slice = try records.toOwnedSlice(allocator);
    errdefer {
        for (records_slice) |*record| {
            record.deinit(allocator);
        }
        allocator.free(records_slice);
    }

    try sortAndValidate(records_slice);

    return .{ .records = records_slice };
}

/// Renders deterministic lockfile text for all plugin records.
pub fn renderLockfile(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(allocator, "# Code generated by `wizig plugin sync`. DO NOT EDIT.\n");
    try out.appendSlice(allocator, "format_version = 1\n\n");

    for (records) |record| {
        try out.appendSlice(allocator, "[[plugins]]\n");
        try out.appendSlice(allocator, "id = ");
        try appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, "\nversion = ");
        try appendQuoted(&out, allocator, record.manifest.version);
        try appendFmt(&out, allocator, "\napi_version = {d}\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "manifest_path = ");
        try appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, "\ncapabilities = ");
        try appendBracketedStringArray(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, "\nios_spm = ");
        try appendBracketedStringArray(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, "\nandroid_maven = ");
        try appendBracketedStringArray(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, "\n\n");
    }

    return out.toOwnedSlice(allocator);
}

/// Renders Zig registrant source from discovered plugins.
pub fn renderZigRegistrant(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(
        allocator,
        "// Code generated by `wizig plugin sync`. DO NOT EDIT.\n\n" ++
            "pub const RegisteredPlugin = struct {\n" ++
            "    id: []const u8,\n" ++
            "    version: []const u8,\n" ++
            "    api_version: u32,\n" ++
            "    manifest_path: []const u8,\n" ++
            "    capabilities: []const []const u8,\n" ++
            "    ios_spm: []const []const u8,\n" ++
            "    android_maven: []const []const u8,\n" ++
            "};\n\n" ++
            "pub const plugins: []const RegisteredPlugin = &.{\n",
    );

    for (records) |record| {
        try out.appendSlice(allocator, "    .{\n");
        try out.appendSlice(allocator, "        .id = ");
        try appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, ",\n        .version = ");
        try appendQuoted(&out, allocator, record.manifest.version);
        try appendFmt(&out, allocator, ",\n        .api_version = {d},\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "        .manifest_path = ");
        try appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, ",\n        .capabilities = ");
        try appendZigStringSlice(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, ",\n        .ios_spm = ");
        try appendZigStringSlice(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, ",\n        .android_maven = ");
        try appendZigStringSlice(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, ",\n    },\n");
    }

    try out.appendSlice(allocator, "};\n");
    return out.toOwnedSlice(allocator);
}

/// Renders Swift registrant source from discovered plugins.
pub fn renderSwiftRegistrant(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(
        allocator,
        "// Code generated by `wizig plugin sync`. DO NOT EDIT.\n" ++
            "import Foundation\n\n" ++
            "public struct PluginDescriptor: Sendable {\n" ++
            "    public let id: String\n" ++
            "    public let version: String\n" ++
            "    public let apiVersion: UInt32\n" ++
            "    public let manifestPath: String\n" ++
            "    public let capabilities: [String]\n" ++
            "    public let iosSpm: [String]\n" ++
            "    public let androidMaven: [String]\n" ++
            "\n" ++
            "    public init(id: String, version: String, apiVersion: UInt32, manifestPath: String, capabilities: [String], iosSpm: [String], androidMaven: [String]) {\n" ++
            "        self.id = id\n" ++
            "        self.version = version\n" ++
            "        self.apiVersion = apiVersion\n" ++
            "        self.manifestPath = manifestPath\n" ++
            "        self.capabilities = capabilities\n" ++
            "        self.iosSpm = iosSpm\n" ++
            "        self.androidMaven = androidMaven\n" ++
            "    }\n" ++
            "}\n\n" ++
            "public enum GeneratedPluginRegistrant {\n" ++
            "    public static let plugins: [PluginDescriptor] = [\n",
    );

    for (records) |record| {
        try out.appendSlice(allocator, "        PluginDescriptor(\n            id: ");
        try appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, ",\n            version: ");
        try appendQuoted(&out, allocator, record.manifest.version);
        try appendFmt(&out, allocator, ",\n            apiVersion: {d},\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "            manifestPath: ");
        try appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, ",\n            capabilities: ");
        try appendBracketedStringArray(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, ",\n            iosSpm: ");
        try appendBracketedStringArray(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, ",\n            androidMaven: ");
        try appendBracketedStringArray(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, "\n        ),\n");
    }

    try out.appendSlice(allocator, "    ]\n}\n");
    return out.toOwnedSlice(allocator);
}

/// Renders Kotlin registrant source from discovered plugins.
pub fn renderKotlinRegistrant(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(
        allocator,
        "// Code generated by `wizig plugin sync`. DO NOT EDIT.\n" ++
            "package dev.wizig\n\n" ++
            "data class PluginDescriptor(\n" ++
            "    val id: String,\n" ++
            "    val version: String,\n" ++
            "    val apiVersion: UInt,\n" ++
            "    val manifestPath: String,\n" ++
            "    val capabilities: List<String>,\n" ++
            "    val iosSpm: List<String>,\n" ++
            "    val androidMaven: List<String>\n" ++
            ")\n\n" ++
            "object GeneratedPluginRegistrant {\n" ++
            "    val plugins: List<PluginDescriptor> = listOf(\n",
    );

    for (records) |record| {
        try out.appendSlice(allocator, "        PluginDescriptor(\n            id = ");
        try appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, ",\n            version = ");
        try appendQuoted(&out, allocator, record.manifest.version);
        try appendFmt(&out, allocator, ",\n            apiVersion = {d}u,\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "            manifestPath = ");
        try appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, ",\n            capabilities = ");
        try appendKotlinList(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, ",\n            iosSpm = ");
        try appendKotlinList(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, ",\n            androidMaven = ");
        try appendKotlinList(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, "\n        ),\n");
    }

    try out.appendSlice(allocator, "    )\n}\n");
    return out.toOwnedSlice(allocator);
}

fn deinitRecordList(allocator: std.mem.Allocator, records: *std.ArrayList(PluginRecord)) void {
    for (records.items) |*record| {
        record.deinit(allocator);
    }
    records.deinit(allocator);
}

fn sortAndValidate(records: []PluginRecord) !void {
    std.mem.sort(PluginRecord, records, {}, lessById);

    var previous: ?[]const u8 = null;
    for (records) |record| {
        if (previous) |prev| {
            if (std.mem.eql(u8, prev, record.manifest.id)) {
                return error.DuplicatePluginId;
            }
        }
        previous = record.manifest.id;
    }
}

fn lessById(_: void, a: PluginRecord, b: PluginRecord) bool {
    return std.mem.order(u8, a.manifest.id, b.manifest.id) == .lt;
}

fn combineManifestPath(
    allocator: std.mem.Allocator,
    root_path: []const u8,
    child_path: []const u8,
) ![]u8 {
    if (std.mem.eql(u8, root_path, ".")) {
        return allocator.dupe(u8, child_path);
    }
    return std.fmt.allocPrint(allocator, "{s}{s}{s}", .{ root_path, std.fs.path.sep_str, child_path });
}

fn appendFmt(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    comptime fmt: []const u8,
    args: anytype,
) !void {
    const text = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(text);
    try out.appendSlice(allocator, text);
}

fn appendQuoted(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: []const u8) !void {
    try out.append(allocator, '"');
    try appendEscaped(out, allocator, value);
    try out.append(allocator, '"');
}

fn appendEscaped(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: []const u8) !void {
    for (value) |ch| {
        switch (ch) {
            '\\' => try out.appendSlice(allocator, "\\\\"),
            '"' => try out.appendSlice(allocator, "\\\""),
            '\n' => try out.appendSlice(allocator, "\\n"),
            '\r' => try out.appendSlice(allocator, "\\r"),
            '\t' => try out.appendSlice(allocator, "\\t"),
            else => try out.append(allocator, ch),
        }
    }
}

fn appendBracketedStringArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const []u8,
) !void {
    try out.append(allocator, '[');
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try appendQuoted(out, allocator, value);
    }
    try out.append(allocator, ']');
}

fn appendKotlinList(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const []u8,
) !void {
    try out.appendSlice(allocator, "listOf(");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try appendQuoted(out, allocator, value);
    }
    try out.append(allocator, ')');
}

fn appendZigStringSlice(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const []u8,
) !void {
    try out.appendSlice(allocator, "&.{");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try appendQuoted(out, allocator, value);
    }
    try out.append(allocator, '}');
}
