//! Swift registrant renderer for discovered plugins.
const std = @import("std");
const MavenDependency = @import("../manifest.zig").MavenDependency;
const SpmDependency = @import("../manifest.zig").SpmDependency;
const PluginRecord = @import("types.zig").PluginRecord;
const common = @import("render_common.zig");

/// Renders Swift registrant source from discovered plugins.
pub fn renderSwiftRegistrant(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(
        allocator,
        "// Code generated by `wizig plugin sync`. DO NOT EDIT.\n" ++
            "import Foundation\n\n" ++
            "public struct SpmDependency: Sendable {\n" ++
            "    public let url: String\n" ++
            "    public let requirement: String\n" ++
            "    public let product: String\n" ++
            "}\n\n" ++
            "public struct MavenDependency: Sendable {\n" ++
            "    public let coordinate: String\n" ++
            "    public let classifier: String\n" ++
            "    public let scope: String\n" ++
            "}\n\n" ++
            "public struct PluginDescriptor: Sendable {\n" ++
            "    public let schemaVersion: UInt32\n" ++
            "    public let id: String\n" ++
            "    public let version: String\n" ++
            "    public let apiVersion: UInt32\n" ++
            "    public let manifestPath: String\n" ++
            "    public let capabilities: [String]\n" ++
            "    public let iosSpm: [SpmDependency]\n" ++
            "    public let androidMaven: [MavenDependency]\n" ++
            "}\n\n" ++
            "public enum GeneratedPluginRegistrant {\n" ++
            "    public static let plugins: [PluginDescriptor] = [\n",
    );

    for (records) |record| {
        try out.appendSlice(allocator, "        PluginDescriptor(\n");
        try common.appendFmt(&out, allocator, "            schemaVersion: {d},\n", .{record.manifest.schema_version});
        try out.appendSlice(allocator, "            id: ");
        try common.appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, ",\n            version: ");
        try common.appendQuoted(&out, allocator, record.manifest.version);
        try common.appendFmt(&out, allocator, ",\n            apiVersion: {d},\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "            manifestPath: ");
        try common.appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, ",\n            capabilities: ");
        try common.appendBracketedStringArray(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, ",\n            iosSpm: ");
        try appendSwiftSpmArray(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, ",\n            androidMaven: ");
        try appendSwiftMavenArray(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, "\n        ),\n");
    }

    try out.appendSlice(allocator, "    ]\n}\n");
    return out.toOwnedSlice(allocator);
}

/// Renders Swift `SpmDependency` array literal.
fn appendSwiftSpmArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const SpmDependency,
) !void {
    try out.append(allocator, '[');
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, "SpmDependency(url: ");
        try common.appendQuoted(out, allocator, value.url);
        try out.appendSlice(allocator, ", requirement: ");
        try common.appendQuoted(out, allocator, value.requirement);
        try out.appendSlice(allocator, ", product: ");
        try common.appendQuoted(out, allocator, value.product);
        try out.append(allocator, ')');
    }
    try out.append(allocator, ']');
}

/// Renders Swift `MavenDependency` array literal.
fn appendSwiftMavenArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const MavenDependency,
) !void {
    try out.append(allocator, '[');
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, "MavenDependency(coordinate: ");
        try common.appendQuoted(out, allocator, value.coordinate);
        try out.appendSlice(allocator, ", classifier: ");
        try common.appendQuoted(out, allocator, value.classifier);
        try out.appendSlice(allocator, ", scope: ");
        try common.appendQuoted(out, allocator, value.scope);
        try out.append(allocator, ')');
    }
    try out.append(allocator, ']');
}
