//! Kotlin registrant renderer for discovered plugins.
const std = @import("std");
const MavenDependency = @import("../manifest.zig").MavenDependency;
const SpmDependency = @import("../manifest.zig").SpmDependency;
const PluginRecord = @import("types.zig").PluginRecord;
const common = @import("render_common.zig");

/// Renders Kotlin registrant source from discovered plugins.
pub fn renderKotlinRegistrant(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(
        allocator,
        "// Code generated by `wizig plugin sync`. DO NOT EDIT.\n" ++
            "package dev.wizig\n\n" ++
            "data class SpmDependency(\n" ++
            "    val url: String,\n" ++
            "    val requirement: String,\n" ++
            "    val product: String\n" ++
            ")\n\n" ++
            "data class MavenDependency(\n" ++
            "    val coordinate: String,\n" ++
            "    val classifier: String,\n" ++
            "    val scope: String\n" ++
            ")\n\n" ++
            "data class PluginDescriptor(\n" ++
            "    val schemaVersion: UInt,\n" ++
            "    val id: String,\n" ++
            "    val version: String,\n" ++
            "    val apiVersion: UInt,\n" ++
            "    val manifestPath: String,\n" ++
            "    val capabilities: List<String>,\n" ++
            "    val iosSpm: List<SpmDependency>,\n" ++
            "    val androidMaven: List<MavenDependency>\n" ++
            ")\n\n" ++
            "object GeneratedPluginRegistrant {\n" ++
            "    val plugins: List<PluginDescriptor> = listOf(\n",
    );

    for (records) |record| {
        try out.appendSlice(allocator, "        PluginDescriptor(\n");
        try common.appendFmt(&out, allocator, "            schemaVersion = {d}u,\n", .{record.manifest.schema_version});
        try out.appendSlice(allocator, "            id = ");
        try common.appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, ",\n            version = ");
        try common.appendQuoted(&out, allocator, record.manifest.version);
        try common.appendFmt(&out, allocator, ",\n            apiVersion = {d}u,\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "            manifestPath = ");
        try common.appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, ",\n            capabilities = ");
        try appendKotlinStringList(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, ",\n            iosSpm = ");
        try appendKotlinSpmArray(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, ",\n            androidMaven = ");
        try appendKotlinMavenArray(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, "\n        ),\n");
    }

    try out.appendSlice(allocator, "    )\n}\n");
    return out.toOwnedSlice(allocator);
}

/// Renders Kotlin `listOf("a", "b")` string list.
fn appendKotlinStringList(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const []u8,
) !void {
    try out.appendSlice(allocator, "listOf(");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try common.appendQuoted(out, allocator, value);
    }
    try out.append(allocator, ')');
}

/// Renders Kotlin `SpmDependency` list literal.
fn appendKotlinSpmArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const SpmDependency,
) !void {
    try out.appendSlice(allocator, "listOf(");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, "SpmDependency(url = ");
        try common.appendQuoted(out, allocator, value.url);
        try out.appendSlice(allocator, ", requirement = ");
        try common.appendQuoted(out, allocator, value.requirement);
        try out.appendSlice(allocator, ", product = ");
        try common.appendQuoted(out, allocator, value.product);
        try out.append(allocator, ')');
    }
    try out.append(allocator, ')');
}

/// Renders Kotlin `MavenDependency` list literal.
fn appendKotlinMavenArray(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const MavenDependency,
) !void {
    try out.appendSlice(allocator, "listOf(");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, "MavenDependency(coordinate = ");
        try common.appendQuoted(out, allocator, value.coordinate);
        try out.appendSlice(allocator, ", classifier = ");
        try common.appendQuoted(out, allocator, value.classifier);
        try out.appendSlice(allocator, ", scope = ");
        try common.appendQuoted(out, allocator, value.scope);
        try out.append(allocator, ')');
    }
    try out.append(allocator, ')');
}
