//! Zig registrant renderer for discovered plugins.
const std = @import("std");
const MavenDependency = @import("../manifest.zig").MavenDependency;
const SpmDependency = @import("../manifest.zig").SpmDependency;
const PluginRecord = @import("types.zig").PluginRecord;
const common = @import("render_common.zig");

/// Renders Zig registrant source from discovered plugins.
pub fn renderZigRegistrant(allocator: std.mem.Allocator, records: []const PluginRecord) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try out.appendSlice(
        allocator,
        "// Code generated by `wizig plugin sync`. DO NOT EDIT.\n\n" ++
            "pub const RegisteredSpmDependency = struct {\n" ++
            "    url: []const u8,\n" ++
            "    requirement: []const u8,\n" ++
            "    product: []const u8,\n" ++
            "};\n\n" ++
            "pub const RegisteredMavenDependency = struct {\n" ++
            "    coordinate: []const u8,\n" ++
            "    classifier: []const u8,\n" ++
            "    scope: []const u8,\n" ++
            "};\n\n" ++
            "pub const RegisteredPlugin = struct {\n" ++
            "    schema_version: u32,\n" ++
            "    id: []const u8,\n" ++
            "    version: []const u8,\n" ++
            "    api_version: u32,\n" ++
            "    manifest_path: []const u8,\n" ++
            "    capabilities: []const []const u8,\n" ++
            "    ios_spm: []const RegisteredSpmDependency,\n" ++
            "    android_maven: []const RegisteredMavenDependency,\n" ++
            "};\n\n" ++
            "pub const plugins: []const RegisteredPlugin = &.{\n",
    );

    for (records) |record| {
        try out.appendSlice(allocator, "    .{\n");
        try common.appendFmt(&out, allocator, "        .schema_version = {d},\n", .{record.manifest.schema_version});
        try out.appendSlice(allocator, "        .id = ");
        try common.appendQuoted(&out, allocator, record.manifest.id);
        try out.appendSlice(allocator, ",\n        .version = ");
        try common.appendQuoted(&out, allocator, record.manifest.version);
        try common.appendFmt(&out, allocator, ",\n        .api_version = {d},\n", .{record.manifest.api_version});
        try out.appendSlice(allocator, "        .manifest_path = ");
        try common.appendQuoted(&out, allocator, record.manifest_path);
        try out.appendSlice(allocator, ",\n        .capabilities = ");
        try appendZigStringSlice(&out, allocator, record.manifest.capabilities);
        try out.appendSlice(allocator, ",\n        .ios_spm = ");
        try appendZigSpmSlice(&out, allocator, record.manifest.ios_spm);
        try out.appendSlice(allocator, ",\n        .android_maven = ");
        try appendZigMavenSlice(&out, allocator, record.manifest.android_maven);
        try out.appendSlice(allocator, ",\n    },\n");
    }

    try out.appendSlice(allocator, "};\n");
    return out.toOwnedSlice(allocator);
}

/// Renders Zig string slice literal `&.{ ... }`.
fn appendZigStringSlice(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const []u8,
) !void {
    try out.appendSlice(allocator, "&.{");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try common.appendQuoted(out, allocator, value);
    }
    try out.append(allocator, '}');
}

/// Renders Zig SPM dependency slice literal.
fn appendZigSpmSlice(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const SpmDependency,
) !void {
    try out.appendSlice(allocator, "&.{");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, ".{ .url = ");
        try common.appendQuoted(out, allocator, value.url);
        try out.appendSlice(allocator, ", .requirement = ");
        try common.appendQuoted(out, allocator, value.requirement);
        try out.appendSlice(allocator, ", .product = ");
        try common.appendQuoted(out, allocator, value.product);
        try out.appendSlice(allocator, " }");
    }
    try out.append(allocator, '}');
}

/// Renders Zig Maven dependency slice literal.
fn appendZigMavenSlice(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    values: []const MavenDependency,
) !void {
    try out.appendSlice(allocator, "&.{");
    for (values, 0..) |value, i| {
        if (i != 0) try out.appendSlice(allocator, ", ");
        try out.appendSlice(allocator, ".{ .coordinate = ");
        try common.appendQuoted(out, allocator, value.coordinate);
        try out.appendSlice(allocator, ", .classifier = ");
        try common.appendQuoted(out, allocator, value.classifier);
        try out.appendSlice(allocator, ", .scope = ");
        try common.appendQuoted(out, allocator, value.scope);
        try out.appendSlice(allocator, " }");
    }
    try out.append(allocator, '}');
}
