//! Renderer for iOS SwiftPM C shim (`Sources/WizigFFI/stub.c`).
//!
//! The shim exports all `wizig_*` symbols referenced by Swift sources and
//! forwards calls to the embedded `WizigFFI.framework` at runtime via `dlopen`.

const std = @import("std");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");

/// Renders C wrappers for runtime + generated API symbols.
pub fn renderIosSwiftPmShim(arena: std.mem.Allocator, spec: api.ApiSpec) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "#include <dlfcn.h>\n");
    try out.appendSlice(arena, "#include <stddef.h>\n");
    try out.appendSlice(arena, "#include <stdint.h>\n");
    try out.appendSlice(arena, "#include <stdio.h>\n");
    try out.appendSlice(arena, "#include \"WizigFFI.h\"\n\n");

    try out.appendSlice(arena, "static void* wizigffi_open_handle(void) {\n");
    try out.appendSlice(arena, "    static void* handle = NULL;\n");
    try out.appendSlice(arena, "    static int attempted = 0;\n");
    try out.appendSlice(arena, "    if (attempted) return handle;\n");
    try out.appendSlice(arena, "    attempted = 1;\n");
    try out.appendSlice(arena, "    handle = dlopen(\"@executable_path/Frameworks/WizigFFI.framework/WizigFFI\", RTLD_NOW | RTLD_LOCAL);\n");
    try out.appendSlice(arena, "    if (handle == NULL) handle = dlopen(\"WizigFFI.framework/WizigFFI\", RTLD_NOW | RTLD_LOCAL);\n");
    try out.appendSlice(arena, "    if (handle == NULL) {\n");
    try out.appendSlice(arena, "        const char* err = dlerror();\n");
    try out.appendSlice(arena, "        fprintf(stderr, \"wizig: WizigFFI.framework load failed: %s\\n\", err ? err : \"(unknown)\");\n");
    try out.appendSlice(arena, "    }\n");
    try out.appendSlice(arena, "    return handle;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "static void* wizigffi_resolve(const char* symbol_name) {\n");
    try out.appendSlice(arena, "    void* handle = wizigffi_open_handle();\n");
    try out.appendSlice(arena, "    if (handle == NULL) return NULL;\n");
    try out.appendSlice(arena, "    return dlsym(handle, symbol_name);\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "uint32_t wizig_ffi_abi_version(void) {\n");
    try out.appendSlice(arena, "    typedef uint32_t (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_abi_version\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : 0;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "const uint8_t* wizig_ffi_contract_hash_ptr(void) {\n");
    try out.appendSlice(arena, "    typedef const uint8_t* (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_contract_hash_ptr\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : NULL;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "size_t wizig_ffi_contract_hash_len(void) {\n");
    try out.appendSlice(arena, "    typedef size_t (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_contract_hash_len\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : 0;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "const uint8_t* wizig_ffi_last_error_domain_ptr(void) {\n");
    try out.appendSlice(arena, "    typedef const uint8_t* (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_last_error_domain_ptr\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : NULL;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "size_t wizig_ffi_last_error_domain_len(void) {\n");
    try out.appendSlice(arena, "    typedef size_t (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_last_error_domain_len\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : 0;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "int32_t wizig_ffi_last_error_code(void) {\n");
    try out.appendSlice(arena, "    typedef int32_t (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_last_error_code\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : 0;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "const uint8_t* wizig_ffi_last_error_message_ptr(void) {\n");
    try out.appendSlice(arena, "    typedef const uint8_t* (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_last_error_message_ptr\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : NULL;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "size_t wizig_ffi_last_error_message_len(void) {\n");
    try out.appendSlice(arena, "    typedef size_t (*fn_t)(void);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_ffi_last_error_message_len\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn() : 0;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "int32_t wizig_runtime_new(const uint8_t* app_name_ptr, size_t app_name_len, WizigRuntimeHandle** out_handle) {\n");
    try out.appendSlice(arena, "    typedef int32_t (*fn_t)(const uint8_t*, size_t, WizigRuntimeHandle**);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_runtime_new\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn(app_name_ptr, app_name_len, out_handle) : -1;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "void wizig_runtime_free(WizigRuntimeHandle* handle) {\n");
    try out.appendSlice(arena, "    typedef void (*fn_t)(WizigRuntimeHandle*);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_runtime_free\");\n");
    try out.appendSlice(arena, "    if (fn != NULL) fn(handle);\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "int32_t wizig_runtime_echo(WizigRuntimeHandle* handle, const uint8_t* input_ptr, size_t input_len, uint8_t** out_ptr, size_t* out_len) {\n");
    try out.appendSlice(arena, "    typedef int32_t (*fn_t)(WizigRuntimeHandle*, const uint8_t*, size_t, uint8_t**, size_t*);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_runtime_echo\");\n");
    try out.appendSlice(arena, "    return fn != NULL ? fn(handle, input_ptr, input_len, out_ptr, out_len) : -1;\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "void wizig_bytes_free(uint8_t* ptr, size_t len) {\n");
    try out.appendSlice(arena, "    typedef void (*fn_t)(uint8_t*, size_t);\n");
    try out.appendSlice(arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"wizig_bytes_free\");\n");
    try out.appendSlice(arena, "    if (fn != NULL) fn(ptr, len);\n");
    try out.appendSlice(arena, "}\n\n");

    for (spec.methods) |method| {
        try appendApiMethodForwarder(&out, arena, method);
    }

    return out.toOwnedSlice(arena);
}

fn appendApiMethodForwarder(
    out: *std.ArrayList(u8),
    arena: std.mem.Allocator,
    method: api.ApiMethod,
) !void {
    const params = try buildMethodParams(arena, method);
    const call_args = try buildMethodCallArgs(arena, method);
    const symbol = try std.fmt.allocPrint(arena, "wizig_api_{s}", .{method.name});

    try helpers.appendFmt(out, arena, "int32_t {s}({s}) {{\n", .{ symbol, params });
    try helpers.appendFmt(out, arena, "    typedef int32_t (*fn_t)({s});\n", .{params});
    try helpers.appendFmt(out, arena, "    fn_t fn = (fn_t)wizigffi_resolve(\"{s}\");\n", .{symbol});
    if (call_args.len == 0) {
        try out.appendSlice(arena, "    return fn != NULL ? fn() : -1;\n");
    } else {
        try helpers.appendFmt(out, arena, "    return fn != NULL ? fn({s}) : -1;\n", .{call_args});
    }
    try out.appendSlice(arena, "}\n\n");
}

fn buildMethodParams(arena: std.mem.Allocator, method: api.ApiMethod) ![]const u8 {
    var params = std.ArrayList(u8).empty;
    var need_comma = false;

    switch (helpers.wireKind(method.input)) {
        .void => {},
        .string => {
            try params.appendSlice(arena, "const uint8_t* input_ptr, size_t input_len");
            need_comma = true;
        },
        .int => {
            try params.appendSlice(arena, "int64_t input");
            need_comma = true;
        },
        .bool => {
            try params.appendSlice(arena, "uint8_t input");
            need_comma = true;
        },
    }

    switch (helpers.wireKind(method.output)) {
        .void => {},
        .string => {
            if (need_comma) try params.appendSlice(arena, ", ");
            try params.appendSlice(arena, "uint8_t** out_ptr, size_t* out_len");
        },
        .int => {
            if (need_comma) try params.appendSlice(arena, ", ");
            try params.appendSlice(arena, "int64_t* out_value");
        },
        .bool => {
            if (need_comma) try params.appendSlice(arena, ", ");
            try params.appendSlice(arena, "uint8_t* out_value");
        },
    }

    return params.toOwnedSlice(arena);
}

fn buildMethodCallArgs(arena: std.mem.Allocator, method: api.ApiMethod) ![]const u8 {
    var args = std.ArrayList(u8).empty;
    var need_comma = false;

    switch (helpers.wireKind(method.input)) {
        .void => {},
        .string => {
            try args.appendSlice(arena, "input_ptr, input_len");
            need_comma = true;
        },
        .int, .bool => {
            try args.appendSlice(arena, "input");
            need_comma = true;
        },
    }

    switch (helpers.wireKind(method.output)) {
        .void => {},
        .string => {
            if (need_comma) try args.appendSlice(arena, ", ");
            try args.appendSlice(arena, "out_ptr, out_len");
        },
        .int, .bool => {
            if (need_comma) try args.appendSlice(arena, ", ");
            try args.appendSlice(arena, "out_value");
        },
    }

    return args.toOwnedSlice(arena);
}
