//! iOS C header and modulemap renderers for framework imports.
//!
//! These artifacts are generated to keep direct C-ABI access available in Xcode
//! while still supporting the higher-level Swift wrapper surface.

const std = @import("std");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");

/// Renders C declarations for all generated `wizig_api_*` exports.
pub fn renderGeneratedApiHeader(arena: std.mem.Allocator, spec: api.ApiSpec) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "#ifndef WIZIG_GENERATED_API_H\n");
    try out.appendSlice(arena, "#define WIZIG_GENERATED_API_H\n\n");
    try out.appendSlice(arena, "#include <stddef.h>\n");
    try out.appendSlice(arena, "#include <stdint.h>\n\n");
    try out.appendSlice(arena, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    for (spec.methods) |method| {
        try helpers.appendFmt(&out, arena, "int32_t wizig_api_{s}(", .{method.name});

        var need_comma = false;
        switch (method.input) {
            .void => {},
            .string => {
                try out.appendSlice(arena, "const uint8_t* input_ptr, size_t input_len");
                need_comma = true;
            },
            .int => {
                try out.appendSlice(arena, "int64_t input");
                need_comma = true;
            },
            .bool => {
                try out.appendSlice(arena, "uint8_t input");
                need_comma = true;
            },
        }

        switch (method.output) {
            .string => {
                if (need_comma) try out.appendSlice(arena, ", ");
                try out.appendSlice(arena, "uint8_t** out_ptr, size_t* out_len");
            },
            .int => {
                if (need_comma) try out.appendSlice(arena, ", ");
                try out.appendSlice(arena, "int64_t* out_value");
            },
            .bool => {
                if (need_comma) try out.appendSlice(arena, ", ");
                try out.appendSlice(arena, "uint8_t* out_value");
            },
            .void => {},
        }

        try out.appendSlice(arena, ");\n");
    }

    try out.appendSlice(arena, "\n#ifdef __cplusplus\n}\n#endif\n\n");
    try out.appendSlice(arena, "#endif\n");
    return out.toOwnedSlice(arena);
}

/// Renders the framework umbrella header that imports runtime + generated APIs.
pub fn renderFrameworkUmbrellaHeader(arena: std.mem.Allocator) ![]u8 {
    return std.fmt.allocPrint(
        arena,
        "// Code generated by `wizig codegen`. DO NOT EDIT.\n" ++
            "#ifndef WIZIG_FFI_FRAMEWORK_H\n" ++
            "#define WIZIG_FFI_FRAMEWORK_H\n\n" ++
            "#include \"wizig.h\"\n" ++
            "#include \"WizigGeneratedApi.h\"\n\n" ++
            "#endif\n",
        .{},
    );
}

/// Renders modulemap for framework-based imports in Swift/ObjC tooling.
pub fn renderFrameworkModuleMap(arena: std.mem.Allocator) ![]u8 {
    return std.fmt.allocPrint(
        arena,
        "framework module WizigFFI {{\n" ++
            "  umbrella header \"WizigFFI.h\"\n" ++
            "  export *\n" ++
            "}}\n",
        .{},
    );
}
