//! Renderer for `WizigGeneratedApi.kt`.
//!
//! User type wire mapping:
//! - `user_struct` <-> JSON `String`
//! - `user_enum`   <-> `Long` raw value

const std = @import("std");
const compatibility = @import("../compatibility.zig");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");
const user_types = @import("kotlin/user_types.zig");

/// Renders the generated Kotlin API facade and native bridge declarations.
pub fn renderKotlinApi(
    arena: std.mem.Allocator,
    spec: api.ApiSpec,
    compat: compatibility.Metadata,
) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "package dev.wizig\n\n");

    try helpers.appendFmt(&out, arena, "private const val WIZIG_EXPECTED_ABI_VERSION: Int = {d}\n", .{compat.abi_version});
    try helpers.appendFmt(&out, arena, "private const val WIZIG_EXPECTED_CONTRACT_HASH: String = \"{s}\"\n\n", .{compat.contract_hash_hex});
    try user_types.appendKotlinTypeDefinitions(&out, arena, spec.structs, spec.enums);

    try out.appendSlice(arena, "interface WizigGeneratedEventSink {\n");
    for (spec.events) |event| {
        try helpers.appendFmt(&out, arena, "    fun on{s}(payload: {s})\n", .{ try helpers.upperCamel(arena, event.name), helpers.kotlinType(event.payload) });
    }
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "class WizigGeneratedFfiException(\n");
    try out.appendSlice(arena, "    val domain: String,\n");
    try out.appendSlice(arena, "    val code: Int,\n");
    try out.appendSlice(arena, "    val detail: String,\n");
    try out.appendSlice(arena, ") : RuntimeException(\"$domain[$code]: $detail\")\n\n");

    try out.appendSlice(arena, "private object WizigGeneratedNativeBridge {\n");
    try out.appendSlice(arena, "    init {\n");
    try out.appendSlice(arena, "        System.loadLibrary(\"wizigffi\")\n");
    try out.appendSlice(arena, "        System.loadLibrary(\"wizigjni\")\n");
    try out.appendSlice(arena, "    }\n\n");
    try out.appendSlice(arena, "    @JvmStatic external fun wizig_validate_bindings()\n");
    for (spec.methods) |method| {
        const ffi_name = try std.fmt.allocPrint(arena, "wizig_api_{s}", .{method.name});
        const output_wire_ty = kotlinWireType(method.output);
        if (method.input == .void) {
            try helpers.appendFmt(&out, arena, "    @JvmStatic external fun {s}(): {s}\n", .{ ffi_name, output_wire_ty });
        } else {
            try helpers.appendFmt(
                &out,
                arena,
                "    @JvmStatic external fun {s}(input: {s}): {s}\n",
                .{ ffi_name, kotlinWireType(method.input), output_wire_ty },
            );
        }
    }
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "class WizigGeneratedApi(\n");
    try out.appendSlice(arena, "    private var sink: WizigGeneratedEventSink? = null,\n");
    try out.appendSlice(arena, ") {\n");
    try out.appendSlice(arena, "    init {\n");
    try out.appendSlice(arena, "        WizigGeneratedNativeBridge\n");
    try out.appendSlice(arena, "        WizigGeneratedNativeBridge.wizig_validate_bindings()\n");
    try out.appendSlice(arena, "    }\n\n");
    try out.appendSlice(arena, "    fun setEventSink(next: WizigGeneratedEventSink?) {\n");
    try out.appendSlice(arena, "        sink = next\n");
    try out.appendSlice(arena, "    }\n\n");

    for (spec.methods) |method| {
        try appendApiMethod(&out, arena, method);
    }

    for (spec.events) |event| {
        const event_name = try helpers.upperCamel(arena, event.name);
        try helpers.appendFmt(&out, arena, "    fun emit{s}(payload: {s}) {{\n", .{ event_name, helpers.kotlinType(event.payload) });
        try helpers.appendFmt(&out, arena, "        sink?.on{s}(payload)\n", .{event_name});
        try out.appendSlice(arena, "    }\n\n");
    }

    try out.appendSlice(arena, "}\n");
    return out.toOwnedSlice(arena);
}

fn appendApiMethod(out: *std.ArrayList(u8), arena: std.mem.Allocator, method: api.ApiMethod) !void {
    const ffi_name = try std.fmt.allocPrint(arena, "wizig_api_{s}", .{method.name});
    if (method.input == .void) {
        if (method.output == .void) {
            try helpers.appendFmt(out, arena, "    fun {s}() {{\n", .{method.name});
            try helpers.appendFmt(out, arena, "        WizigGeneratedNativeBridge.{s}()\n", .{ffi_name});
            try out.appendSlice(arena, "    }\n\n");
            return;
        }
        try helpers.appendFmt(out, arena, "    fun {s}(): {s} {{\n", .{ method.name, helpers.kotlinType(method.output) });
        const call_expr = try std.fmt.allocPrint(arena, "WizigGeneratedNativeBridge.{s}()", .{ffi_name});
        try appendOutputReturn(out, arena, method.output, call_expr);
        try out.appendSlice(arena, "    }\n\n");
        return;
    }

    try helpers.appendFmt(out, arena, "    fun {s}(input: {s})", .{ method.name, helpers.kotlinType(method.input) });
    if (method.output != .void) {
        try helpers.appendFmt(out, arena, ": {s}", .{helpers.kotlinType(method.output)});
    }
    try out.appendSlice(arena, " {\n");

    const wire_input = switch (method.input) {
        .user_struct => |name| blk: {
            _ = name;
            try out.appendSlice(arena, "        val wireInput = input.toJson()\n");
            break :blk "wireInput";
        },
        .user_enum => blk: {
            try out.appendSlice(arena, "        val wireInput = input.rawValue\n");
            break :blk "wireInput";
        },
        else => "input",
    };

    const call_expr = try std.fmt.allocPrint(arena, "WizigGeneratedNativeBridge.{s}({s})", .{ ffi_name, wire_input });
    if (method.output == .void) {
        try helpers.appendFmt(out, arena, "        {s}\n", .{call_expr});
    } else {
        try appendOutputReturn(out, arena, method.output, call_expr);
    }
    try out.appendSlice(arena, "    }\n\n");
}

fn appendOutputReturn(
    out: *std.ArrayList(u8),
    arena: std.mem.Allocator,
    output: api.ApiType,
    call_expr: []const u8,
) !void {
    switch (output) {
        .user_struct => |name| {
            try helpers.appendFmt(out, arena, "        val wireOutput = {s}\n", .{call_expr});
            try helpers.appendFmt(out, arena, "        return {s}.fromJson(wireOutput)\n", .{name});
        },
        .user_enum => |name| {
            try helpers.appendFmt(out, arena, "        val wireOutput = {s}\n", .{call_expr});
            try helpers.appendFmt(out, arena, "        return {s}.fromRaw(wireOutput)\n", .{name});
        },
        else => {
            try helpers.appendFmt(out, arena, "        return {s}\n", .{call_expr});
        },
    }
}

fn kotlinWireType(value: api.ApiType) []const u8 {
    return switch (helpers.wireKind(value)) {
        .string => "String",
        .int => "Long",
        .bool => "Boolean",
        .void => "Unit",
    };
}
