//! Renderer for `WizigGeneratedApi.swift`.

const std = @import("std");
const compatibility = @import("../compatibility.zig");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");
const ffi_class = @import("swift/ffi_class.zig");
const api_class_core = @import("swift/api_class_core.zig");
const api_class_methods = @import("swift/api_class_methods.zig");

pub fn renderSwiftApi(
    arena: std.mem.Allocator,
    spec: api.ApiSpec,
    compat: compatibility.Metadata,
) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "import Darwin\n");
    try out.appendSlice(arena, "import Foundation\n\n");

    try helpers.appendFmt(&out, arena, "private let wizigExpectedAbiVersion: UInt32 = {d}\n", .{compat.abi_version});
    try helpers.appendFmt(&out, arena, "private let wizigExpectedContractHash = \"{s}\"\n\n", .{compat.contract_hash_hex});

    try out.appendSlice(arena, "public protocol WizigGeneratedEventSink: AnyObject {\n");
    for (spec.events) |event| {
        const event_name = try helpers.upperCamel(arena, event.name);
        try helpers.appendFmt(&out, arena, "    func on{s}(payload: {s})\n", .{ event_name, helpers.swiftType(event.payload) });
    }
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "public enum WizigGeneratedApiError: Error, CustomStringConvertible {\n");
    try out.appendSlice(arena, "    case ffiLibraryLoadFailed(String)\n");
    try out.appendSlice(arena, "    case ffiSymbolMissing(String)\n");
    try out.appendSlice(arena, "    case ffiCallFailed(function: String, domain: String, code: Int32, message: String)\n");
    try out.appendSlice(arena, "    case compatibilityMismatch(expectedAbi: UInt32, actualAbi: UInt32, expectedContractHash: String, actualContractHash: String)\n");
    try out.appendSlice(arena, "    case bindingValidationFailed(String)\n");
    try out.appendSlice(arena, "    case invalidUtf8(function: String)\n");
    try out.appendSlice(arena, "    case unexpectedNullOutput(function: String)\n\n");
    try out.appendSlice(arena, "    public var description: String {\n");
    try out.appendSlice(arena, "        switch self {\n");
    try out.appendSlice(arena, "        case let .ffiLibraryLoadFailed(reason):\n");
    try out.appendSlice(arena, "            return \"failed to load Wizig FFI library: \\(reason)\"\n");
    try out.appendSlice(arena, "        case let .ffiSymbolMissing(name):\n");
    try out.appendSlice(arena, "            return \"missing Wizig FFI symbol: \\(name)\"\n");
    try out.appendSlice(arena, "        case let .ffiCallFailed(function, domain, code, message):\n");
    try out.appendSlice(arena, "            return \"FFI call failed: \\(function) domain=\\(domain) code=\\(code) message=\\(message)\"\n");
    try out.appendSlice(arena, "        case let .compatibilityMismatch(expectedAbi, actualAbi, expectedContractHash, actualContractHash):\n");
    try out.appendSlice(arena, "            return \"FFI compatibility mismatch: abi expected \\(expectedAbi), got \\(actualAbi); contract expected \\(expectedContractHash), got \\(actualContractHash)\"\n");
    try out.appendSlice(arena, "        case let .bindingValidationFailed(reason):\n");
    try out.appendSlice(arena, "            return \"Wizig generated API binding validation failed: \\(reason)\"\n");
    try out.appendSlice(arena, "        case let .invalidUtf8(function):\n");
    try out.appendSlice(arena, "            return \"\\(function) returned non-UTF-8 output\"\n");
    try out.appendSlice(arena, "        case let .unexpectedNullOutput(function):\n");
    try out.appendSlice(arena, "            return \"\\(function) returned null output\"\n");
    try out.appendSlice(arena, "        }\n");
    try out.appendSlice(arena, "    }\n");
    try out.appendSlice(arena, "}\n\n");

    try out.appendSlice(arena, "private enum WizigGeneratedStatus: Int32 {\n");
    try out.appendSlice(arena, "    case ok = 0\n");
    try out.appendSlice(arena, "}\n\n");

    try ffi_class.appendFfiClass(&out, arena);
    try api_class_core.appendApiClassCore(&out, arena, spec.methods);
    try api_class_methods.appendApiClassMethods(&out, arena, spec);

    return out.toOwnedSlice(arena);
}
