//! Renderer for `lib/WizigGeneratedAppModule.zig`.

const std = @import("std");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");

const ZigWrapperShape = struct {
    args: []const u8,
    call_args: []const u8,
    return_ty: []const u8,
};

pub fn renderZigAppModule(
    arena: std.mem.Allocator,
    spec: api.ApiSpec,
    module_imports: []const []const u8,
) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "const std = @import(\"std\");\n\n");

    for (module_imports, 0..) |import_path, idx| {
        try helpers.appendFmt(&out, arena, "const module_{d} = @import(\"{s}\");\n", .{ idx, import_path });
    }
    if (module_imports.len > 0) {
        try out.appendSlice(arena, "\n");
    }

    const main_module_path = "main.zig";
    const main_module_index = blk: {
        for (module_imports, 0..) |import_path, idx| {
            if (std.mem.eql(u8, import_path, main_module_path)) break :blk idx;
        }
        break :blk @as(?usize, null);
    };

    for (spec.methods) |method| {
        const shape = try zigWrapperShape(arena, method);
        if (shape.args.len == 0) {
            try helpers.appendFmt(&out, arena, "pub fn {s}() {s} {{\n", .{ method.name, shape.return_ty });
        } else {
            try helpers.appendFmt(&out, arena, "pub fn {s}({s}) {s} {{\n", .{ method.name, shape.args, shape.return_ty });
        }

        const indent = if (main_module_index != null) "        " else "    ";
        if (main_module_index) |idx| {
            if (shape.call_args.len == 0) {
                try helpers.appendFmt(
                    &out,
                    arena,
                    "    if (@hasDecl(module_{d}, \"{s}\")) return module_{d}.{s}();\n",
                    .{ idx, method.name, idx, method.name },
                );
            } else {
                try helpers.appendFmt(
                    &out,
                    arena,
                    "    if (@hasDecl(module_{d}, \"{s}\")) return module_{d}.{s}({s});\n",
                    .{ idx, method.name, idx, method.name, shape.call_args },
                );
            }
            try helpers.appendFmt(&out, arena, "    if (!@hasDecl(module_{d}, \"{s}\")) {{\n", .{ idx, method.name });
        }

        try helpers.appendFmt(&out, arena, "{s}const candidate_count: comptime_int = 0", .{indent});
        for (module_imports, 0..) |_, idx| {
            if (main_module_index != null and idx == main_module_index.?) continue;
            try helpers.appendFmt(
                &out,
                arena,
                " + @as(comptime_int, if (@hasDecl(module_{d}, \"{s}\")) 1 else 0)",
                .{ idx, method.name },
            );
        }
        try out.appendSlice(arena, ";\n");

        try helpers.appendFmt(
            &out,
            arena,
            "{s}if (candidate_count == 0) @compileError(\"wizig codegen: no implementation found for API method '{s}' across lib/**/*.zig\");\n",
            .{ indent, method.name },
        );
        try helpers.appendFmt(
            &out,
            arena,
            "{s}if (candidate_count > 1) @compileError(\"wizig codegen: multiple implementations found for API method '{s}' across lib/**/*.zig (define once, or keep only lib/main.zig)\");\n",
            .{ indent, method.name },
        );

        for (module_imports, 0..) |_, idx| {
            if (main_module_index != null and idx == main_module_index.?) continue;
            if (shape.call_args.len == 0) {
                try helpers.appendFmt(
                    &out,
                    arena,
                    "{s}if (@hasDecl(module_{d}, \"{s}\")) return module_{d}.{s}();\n",
                    .{ indent, idx, method.name, idx, method.name },
                );
            } else {
                try helpers.appendFmt(
                    &out,
                    arena,
                    "{s}if (@hasDecl(module_{d}, \"{s}\")) return module_{d}.{s}({s});\n",
                    .{ indent, idx, method.name, idx, method.name, shape.call_args },
                );
            }
        }

        try helpers.appendFmt(&out, arena, "{s}unreachable;\n", .{indent});
        if (main_module_index != null) {
            try out.appendSlice(arena, "    }\n");
        }
        try out.appendSlice(arena, "}\n\n");
    }

    return out.toOwnedSlice(arena);
}

fn zigWrapperShape(arena: std.mem.Allocator, method: api.ApiMethod) !ZigWrapperShape {
    const output_ty = helpers.zigType(method.output);
    const return_ty = switch (method.output) {
        .void => "!void",
        else => try std.fmt.allocPrint(arena, "!{s}", .{output_ty}),
    };

    return switch (method.input) {
        .void => if (method.output == .string)
            .{ .args = "allocator: std.mem.Allocator", .call_args = "allocator", .return_ty = return_ty }
        else
            .{ .args = "", .call_args = "", .return_ty = return_ty },
        .string => if (method.output == .string)
            .{ .args = "input: []const u8, allocator: std.mem.Allocator", .call_args = "input, allocator", .return_ty = return_ty }
        else
            .{ .args = "input: []const u8", .call_args = "input", .return_ty = return_ty },
        .int => if (method.output == .string)
            .{ .args = "input: i64, allocator: std.mem.Allocator", .call_args = "input, allocator", .return_ty = return_ty }
        else
            .{ .args = "input: i64", .call_args = "input", .return_ty = return_ty },
        .bool => if (method.output == .string)
            .{ .args = "input: bool, allocator: std.mem.Allocator", .call_args = "input, allocator", .return_ty = return_ty }
        else
            .{ .args = "input: bool", .call_args = "input", .return_ty = return_ty },
        .user_struct => |name| if (method.output == .string)
            .{
                .args = try std.fmt.allocPrint(arena, "input: {s}, allocator: std.mem.Allocator", .{name}),
                .call_args = "input, allocator",
                .return_ty = return_ty,
            }
        else
            .{
                .args = try std.fmt.allocPrint(arena, "input: {s}", .{name}),
                .call_args = "input",
                .return_ty = return_ty,
            },
        .user_enum => |name| if (method.output == .string)
            .{
                .args = try std.fmt.allocPrint(arena, "input: {s}, allocator: std.mem.Allocator", .{name}),
                .call_args = "input, allocator",
                .return_ty = return_ty,
            }
        else
            .{
                .args = try std.fmt.allocPrint(arena, "input: {s}", .{name}),
                .call_args = "input",
                .return_ty = return_ty,
            },
    };
}
