//! Renderer for `WizigGeneratedApi.zig`.

const std = @import("std");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");

pub fn renderZigApi(arena: std.mem.Allocator, spec: api.ApiSpec) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "const std = @import(\"std\");\n\n");

    try out.appendSlice(arena, "pub const WizigGeneratedApi = struct {\n");
    try out.appendSlice(arena, "    pub fn init() WizigGeneratedApi {\n");
    try out.appendSlice(arena, "        return .{};\n");
    try out.appendSlice(arena, "    }\n\n");

    for (spec.methods) |method| {
        const input_ty = helpers.zigType(method.input);
        const output_ty = helpers.zigType(method.output);
        if (method.output == .void) {
            try helpers.appendFmt(&out, arena, "    pub fn {s}(self: *const WizigGeneratedApi, input: {s}) void {{\n", .{ method.name, input_ty });
            try out.appendSlice(arena, "        _ = self;\n");
            try out.appendSlice(arena, "        _ = input;\n");
            try out.appendSlice(arena, "    }\n\n");
        } else {
            try helpers.appendFmt(&out, arena, "    pub fn {s}(self: *const WizigGeneratedApi, input: {s}, allocator: std.mem.Allocator) !{s} {{\n", .{ method.name, input_ty, output_ty });
            try out.appendSlice(arena, "        _ = self;\n");
            try out.appendSlice(arena, "        _ = allocator;\n");
            if (method.output == .string and method.input == .string) {
                try out.appendSlice(arena, "        return allocator.dupe(u8, input);\n");
            } else {
                try helpers.appendFmt(&out, arena, "        _ = input;\n        return {s};\n", .{helpers.zigDefaultValue(method.output)});
            }
            try out.appendSlice(arena, "    }\n\n");
        }
    }

    try out.appendSlice(arena, "};\n");
    return out.toOwnedSlice(arena);
}
