//! Renderer for generated Zig FFI root module.

const std = @import("std");
const compatibility = @import("../compatibility.zig");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");
const preamble = @import("zig_ffi_root_preamble.zig");
const methods = @import("zig_ffi_root_methods.zig");

pub fn renderZigFfiRoot(
    arena: std.mem.Allocator,
    spec: api.ApiSpec,
    compat: compatibility.Metadata,
) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "const std = @import(\"std\");\n");
    try out.appendSlice(arena, "const app = @import(\"wizig_app\");\n\n");

    try helpers.appendFmt(&out, arena, "const wizig_generated_abi_version: u32 = {d};\n", .{compat.abi_version});
    try helpers.appendFmt(&out, arena, "const wizig_generated_contract_hash: []const u8 = \"{s}\";\n\n", .{compat.contract_hash_hex});

    try preamble.appendPrelude(&out, arena);
    try methods.appendMethodExports(&out, arena, spec.methods);

    return out.toOwnedSlice(arena);
}
