// Code generated by `ziggy plugin sync`. DO NOT EDIT.
import Foundation

public struct PluginDescriptor: Sendable {
    public let id: String
    public let version: String
    public let apiVersion: UInt32
    public let manifestPath: String
    public let capabilities: [String]
    public let iosSpm: [String]
    public let androidMaven: [String]

    public init(id: String, version: String, apiVersion: UInt32, manifestPath: String, capabilities: [String], iosSpm: [String], androidMaven: [String]) {
        self.id = id
        self.version = version
        self.apiVersion = apiVersion
        self.manifestPath = manifestPath
        self.capabilities = capabilities
        self.iosSpm = iosSpm
        self.androidMaven = androidMaven
    }
}

public enum GeneratedPluginRegistrant {
    public static let plugins: [PluginDescriptor] = [
        PluginDescriptor(
            id: "dev.ziggy.hello",
            version: "0.1.0",
            apiVersion: 1,
            manifestPath: "examples/plugin-hello/ziggy-plugin.toml",
            capabilities: ["log"],
            iosSpm: [],
            androidMaven: []
        ),
    ]
}
