//! Swift `WizigGeneratedFFI` helper class renderer.

const std = @import("std");

pub fn appendFfiClass(out: *std.ArrayList(u8), arena: std.mem.Allocator) !void {
    try out.appendSlice(arena, "private final class WizigGeneratedFFI {\n");
    try out.appendSlice(arena, "    typealias BytesFreeFn = @convention(c) (UnsafeMutablePointer<UInt8>?, Int) -> Void\n\n");
    try out.appendSlice(arena, "    typealias AbiVersionFn = @convention(c) () -> UInt32\n");
    try out.appendSlice(arena, "    typealias ContractHashPtrFn = @convention(c) () -> UnsafePointer<UInt8>\n");
    try out.appendSlice(arena, "    typealias ContractHashLenFn = @convention(c) () -> Int\n");
    try out.appendSlice(arena, "    typealias LastErrorDomainPtrFn = @convention(c) () -> UnsafePointer<UInt8>\n");
    try out.appendSlice(arena, "    typealias LastErrorDomainLenFn = @convention(c) () -> Int\n");
    try out.appendSlice(arena, "    typealias LastErrorCodeFn = @convention(c) () -> Int32\n");
    try out.appendSlice(arena, "    typealias LastErrorMessagePtrFn = @convention(c) () -> UnsafePointer<UInt8>\n");
    try out.appendSlice(arena, "    typealias LastErrorMessageLenFn = @convention(c) () -> Int\n\n");
    try out.appendSlice(arena, "    let bytesFree: BytesFreeFn\n");
    try out.appendSlice(arena, "    let abiVersion: AbiVersionFn\n");
    try out.appendSlice(arena, "    let contractHashPtr: ContractHashPtrFn\n");
    try out.appendSlice(arena, "    let contractHashLen: ContractHashLenFn\n");
    try out.appendSlice(arena, "    let lastErrorDomainPtr: LastErrorDomainPtrFn\n");
    try out.appendSlice(arena, "    let lastErrorDomainLen: LastErrorDomainLenFn\n");
    try out.appendSlice(arena, "    let lastErrorCode: LastErrorCodeFn\n");
    try out.appendSlice(arena, "    let lastErrorMessagePtr: LastErrorMessagePtrFn\n");
    try out.appendSlice(arena, "    let lastErrorMessageLen: LastErrorMessageLenFn\n");
    try out.appendSlice(arena, "    private let libraryHandle: UnsafeMutableRawPointer\n\n");
    try out.appendSlice(arena, "    private static func defaultLibraryCandidates() -> [String] {\n");
    try out.appendSlice(arena, "        var values = [String]()\n");
    try out.appendSlice(arena, "        if let fromEnv = ProcessInfo.processInfo.environment[\"WIZIG_FFI_LIB\"], !fromEnv.isEmpty {\n");
    try out.appendSlice(arena, "            values.append(fromEnv)\n");
    try out.appendSlice(arena, "        }\n");
    try out.appendSlice(arena, "        if let frameworksPath = Bundle.main.privateFrameworksPath, !frameworksPath.isEmpty {\n");
    try out.appendSlice(arena, "            values.append((frameworksPath as NSString).appendingPathComponent(\"WizigFFI.framework/WizigFFI\"))\n");
    try out.appendSlice(arena, "        }\n");
    try out.appendSlice(arena, "        values.append(Bundle.main.bundleURL.appendingPathComponent(\"Frameworks/WizigFFI.framework/WizigFFI\").path)\n");
    try out.appendSlice(arena, "        if let executableDir = Bundle.main.executableURL?.deletingLastPathComponent().path {\n");
    try out.appendSlice(arena, "            values.append((executableDir as NSString).appendingPathComponent(\"Frameworks/WizigFFI.framework/WizigFFI\"))\n");
    try out.appendSlice(arena, "        }\n");
    try out.appendSlice(arena, "        values.append(contentsOf: [\n");
    try out.appendSlice(arena, "            \"@rpath/WizigFFI.framework/WizigFFI\",\n");
    try out.appendSlice(arena, "            \"@executable_path/Frameworks/WizigFFI.framework/WizigFFI\",\n");
    try out.appendSlice(arena, "        ])\n");
    try out.appendSlice(arena, "        var seen = Set<String>()\n");
    try out.appendSlice(arena, "        return values.filter { candidate in\n");
    try out.appendSlice(arena, "            guard !candidate.isEmpty else { return false }\n");
    try out.appendSlice(arena, "            return seen.insert(candidate).inserted\n");
    try out.appendSlice(arena, "        }\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    init(libraryPath: String?) throws {\n");
    try out.appendSlice(arena, "        let candidates: [String] = {\n");
    try out.appendSlice(arena, "            if let libraryPath, !libraryPath.isEmpty {\n");
    try out.appendSlice(arena, "                return [libraryPath]\n");
    try out.appendSlice(arena, "            }\n");
    try out.appendSlice(arena, "            return Self.defaultLibraryCandidates()\n");
    try out.appendSlice(arena, "        }()\n\n");
    try out.appendSlice(arena, "        var attempts = [String]()\n");
    try out.appendSlice(arena, "        for candidate in candidates {\n");
    try out.appendSlice(arena, "            _ = dlerror()\n");
    try out.appendSlice(arena, "            guard let loaded = dlopen(candidate, RTLD_NOW | RTLD_LOCAL) else {\n");
    try out.appendSlice(arena, "                if let err = dlerror() {\n");
    try out.appendSlice(arena, "                    attempts.append(\"\\(candidate): \\(String(cString: err))\")\n");
    try out.appendSlice(arena, "                } else {\n");
    try out.appendSlice(arena, "                    attempts.append(\"\\(candidate): unknown dlopen error\")\n");
    try out.appendSlice(arena, "                }\n");
    try out.appendSlice(arena, "                continue\n");
    try out.appendSlice(arena, "            }\n");
    try out.appendSlice(arena, "            do {\n");
    try out.appendSlice(arena, "                let bytesFree: BytesFreeFn = try Self.loadSymbol(loaded, name: \"wizig_bytes_free\")\n");
    try out.appendSlice(arena, "                let abiVersion: AbiVersionFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_abi_version\")\n");
    try out.appendSlice(arena, "                let contractHashPtr: ContractHashPtrFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_contract_hash_ptr\")\n");
    try out.appendSlice(arena, "                let contractHashLen: ContractHashLenFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_contract_hash_len\")\n");
    try out.appendSlice(arena, "                let lastErrorDomainPtr: LastErrorDomainPtrFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_last_error_domain_ptr\")\n");
    try out.appendSlice(arena, "                let lastErrorDomainLen: LastErrorDomainLenFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_last_error_domain_len\")\n");
    try out.appendSlice(arena, "                let lastErrorCode: LastErrorCodeFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_last_error_code\")\n");
    try out.appendSlice(arena, "                let lastErrorMessagePtr: LastErrorMessagePtrFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_last_error_message_ptr\")\n");
    try out.appendSlice(arena, "                let lastErrorMessageLen: LastErrorMessageLenFn = try Self.loadSymbol(loaded, name: \"wizig_ffi_last_error_message_len\")\n");
    try out.appendSlice(arena, "                self.libraryHandle = loaded\n");
    try out.appendSlice(arena, "                self.bytesFree = bytesFree\n");
    try out.appendSlice(arena, "                self.abiVersion = abiVersion\n");
    try out.appendSlice(arena, "                self.contractHashPtr = contractHashPtr\n");
    try out.appendSlice(arena, "                self.contractHashLen = contractHashLen\n");
    try out.appendSlice(arena, "                self.lastErrorDomainPtr = lastErrorDomainPtr\n");
    try out.appendSlice(arena, "                self.lastErrorDomainLen = lastErrorDomainLen\n");
    try out.appendSlice(arena, "                self.lastErrorCode = lastErrorCode\n");
    try out.appendSlice(arena, "                self.lastErrorMessagePtr = lastErrorMessagePtr\n");
    try out.appendSlice(arena, "                self.lastErrorMessageLen = lastErrorMessageLen\n");
    try out.appendSlice(arena, "                return\n");
    try out.appendSlice(arena, "            } catch {\n");
    try out.appendSlice(arena, "                _ = dlclose(loaded)\n");
    try out.appendSlice(arena, "                attempts.append(\"\\(candidate): \\(error)\")\n");
    try out.appendSlice(arena, "            }\n");
    try out.appendSlice(arena, "        }\n\n");
    try out.appendSlice(arena, "        let details = attempts.isEmpty ? \"no candidate library path\" : attempts.joined(separator: \" | \")\n");
    try out.appendSlice(arena, "        throw WizigGeneratedApiError.ffiLibraryLoadFailed(details)\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    deinit {\n");
    try out.appendSlice(arena, "        _ = dlclose(libraryHandle)\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    func loadSymbol<T>(_ name: String, as: T.Type = T.self) throws -> T {\n");
    try out.appendSlice(arena, "        try Self.loadSymbol(libraryHandle, name: name)\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    private static func loadSymbol<T>(_ handle: UnsafeMutableRawPointer, name: String) throws -> T {\n");
    try out.appendSlice(arena, "        _ = dlerror()\n");
    try out.appendSlice(arena, "        guard let symbol = dlsym(handle, name) else {\n");
    try out.appendSlice(arena, "            throw WizigGeneratedApiError.ffiSymbolMissing(name)\n");
    try out.appendSlice(arena, "        }\n");
    try out.appendSlice(arena, "        return unsafeBitCast(symbol, to: T.self)\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    private func decodeUtf8(ptr: UnsafePointer<UInt8>, len: Int) -> String {\n");
    try out.appendSlice(arena, "        guard len > 0 else { return \"\" }\n");
    try out.appendSlice(arena, "        let data = Data(bytes: ptr, count: len)\n");
    try out.appendSlice(arena, "        return String(data: data, encoding: .utf8) ?? \"\"\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    func readContractHash() -> String {\n");
    try out.appendSlice(arena, "        decodeUtf8(ptr: contractHashPtr(), len: contractHashLen())\n");
    try out.appendSlice(arena, "    }\n\n");

    try out.appendSlice(arena, "    func readLastError() -> (domain: String, code: Int32, message: String) {\n");
    try out.appendSlice(arena, "        let domain = decodeUtf8(ptr: lastErrorDomainPtr(), len: lastErrorDomainLen())\n");
    try out.appendSlice(arena, "        let code = lastErrorCode()\n");
    try out.appendSlice(arena, "        let message = decodeUtf8(ptr: lastErrorMessagePtr(), len: lastErrorMessageLen())\n");
    try out.appendSlice(arena, "        return (domain, code, message)\n");
    try out.appendSlice(arena, "    }\n");
    try out.appendSlice(arena, "}\n\n");
}
