//! Renderer for generated Android JNI bridge C source.

const std = @import("std");
const compatibility = @import("../compatibility.zig");
const api = @import("../model/api.zig");
const helpers = @import("helpers.zig");
const base_sections = @import("android_jni/base_sections.zig");
const method_exports = @import("android_jni/method_exports.zig");

pub fn renderAndroidJniBridge(
    arena: std.mem.Allocator,
    spec: api.ApiSpec,
    compat: compatibility.Metadata,
) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(arena);

    try out.appendSlice(arena, "// Code generated by `wizig codegen`. DO NOT EDIT.\n");
    try out.appendSlice(arena, "#include <jni.h>\n");
    try out.appendSlice(arena, "#include <stdint.h>\n");
    try out.appendSlice(arena, "#include <stdbool.h>\n");
    try out.appendSlice(arena, "#include <stdlib.h>\n");
    try out.appendSlice(arena, "#include <string.h>\n");
    try out.appendSlice(arena, "#include <stdio.h>\n");
    try out.appendSlice(arena, "#include <dlfcn.h>\n");
    try out.appendSlice(arena, "#if defined(__ANDROID__)\n");
    try out.appendSlice(arena, "#include <android/log.h>\n");
    try out.appendSlice(arena, "#include <pthread.h>\n");
    try out.appendSlice(arena, "#include <unistd.h>\n");
    try out.appendSlice(arena, "#endif\n\n");

    try helpers.appendFmt(&out, arena, "#define WIZIG_EXPECTED_ABI_VERSION {d}\n", .{compat.abi_version});
    try helpers.appendFmt(&out, arena, "#define WIZIG_EXPECTED_CONTRACT_HASH \"{s}\"\n\n", .{compat.contract_hash_hex});

    try out.appendSlice(arena, "extern void wizig_bytes_free(uint8_t* ptr, size_t len);\n");
    try out.appendSlice(arena, "extern uint32_t wizig_ffi_abi_version(void);\n");
    try out.appendSlice(arena, "extern const uint8_t* wizig_ffi_contract_hash_ptr(void);\n");
    try out.appendSlice(arena, "extern size_t wizig_ffi_contract_hash_len(void);\n");
    try out.appendSlice(arena, "extern const uint8_t* wizig_ffi_last_error_domain_ptr(void);\n");
    try out.appendSlice(arena, "extern size_t wizig_ffi_last_error_domain_len(void);\n");
    try out.appendSlice(arena, "extern int32_t wizig_ffi_last_error_code(void);\n");
    try out.appendSlice(arena, "extern const uint8_t* wizig_ffi_last_error_message_ptr(void);\n");
    try out.appendSlice(arena, "extern size_t wizig_ffi_last_error_message_len(void);\n");

    for (spec.methods) |method| {
        const ffi_name = try std.fmt.allocPrint(arena, "wizig_api_{s}", .{method.name});
        try helpers.appendFmt(&out, arena, "extern int32_t {s}(", .{ffi_name});
        var need_comma = false;
        switch (helpers.wireKind(method.input)) {
            .void => {},
            .string => {
                try out.appendSlice(arena, "const uint8_t* input_ptr, size_t input_len");
                need_comma = true;
            },
            .int => {
                try out.appendSlice(arena, "int64_t input");
                need_comma = true;
            },
            .bool => {
                try out.appendSlice(arena, "uint8_t input");
                need_comma = true;
            },
        }

        switch (helpers.wireKind(method.output)) {
            .string => {
                if (need_comma) try out.appendSlice(arena, ", ");
                try out.appendSlice(arena, "uint8_t** out_ptr, size_t* out_len");
            },
            .int => {
                if (need_comma) try out.appendSlice(arena, ", ");
                try out.appendSlice(arena, "int64_t* out_value");
            },
            .bool => {
                if (need_comma) try out.appendSlice(arena, ", ");
                try out.appendSlice(arena, "uint8_t* out_value");
            },
            .void => {},
        }

        try out.appendSlice(arena, ");\n");
    }
    try out.appendSlice(arena, "\n");

    try base_sections.appendBaseSections(&out, arena, spec.methods);
    try method_exports.appendMethodExports(&out, arena, spec.methods);

    return out.toOwnedSlice(arena);
}
